# Site Settings
name: 'Rayean Mahmud Arnob'
description: 'Cross-platform Mobile App Developer & Tech Storyteller. Passionate about Flutter, Python, Firebase, and AI.'
logo: '/assets/images/avatar1.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: ''  # Leave empty for user.github.io root sites
url: 'https://rayean-mahmud.github.io'
disqus: https-rayean-mahmud-github-io  # You can add Disqus shortname here if needed
email: 'rayean.dev@gmail.com'
mailchimp-list: ''  # Add your Mailchimp URL here if needed

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Author Info
authors:
  rayean:
    name: Rayean Mahmud Arnob
    avatar: /assets/images/avatar1.jpg
    bio: "Rayean is a cross-platform Mobile App Developer focused on building seamless digital experiences with Flutter, Firebase, and clean UI/UX. Beyond coding, he enjoys writing insightful tech content that bridges creativity and functionality."
    site: https://github.com/Rayean-Mahmud
    email: rayean.dev@gmail.com
    github: https://github.com/Rayean-Mahmud
    linkedin: https://www.linkedin.com/in/rayean-mahmud-arnob-a78345173/


# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: rayean
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: "_pages"
    values:
      layout: page

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10

# Exclude metadata and dev files
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
