# Site Settings
name: 'Rayean Mahmud Arnob'
description: 'Cross-platform Mobile App Developer & Tech Storyteller. Passionate about Flutter, Python, Firebase, and AI.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''  # Leave empty for user.github.io root sites
url: 'https://rayean-mahmud.github.io'
disqus: ''  # You can add Disqus shortname here if needed
email: 'rayean.dev@gmail.com'
mailchimp-list: ''  # Add your Mailchimp URL here if needed

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Author Info
authors:
  rayean:
    name: Rayean Mahmud Arnob
    site: https://github.com/Rayean-Mahmud
    avatar: /assets/images/avatar1.jpg  # Replace with your actual image path
    bio: "Cross-platform Mobile Application developer with a passion for Flutter, Python, Firebase, UI/UX, Writing and building meaningful digital experiences."
    email: rayean.dev@gmail.com # Replace or remove if not used
    github: https://github.com/Rayean-Mahmud
    linkedin: https://www.linkedin.com/in/rayean-mahmud-arnob-a78345173/

# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Rayean
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: "_pages"
    values:
      layout: page

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10

# Exclude metadata and dev files
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
